# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 1) do

  create_table "accounts", :force => true do |t|
    t.column "name", :string, :limit => 200, :default => "", :null => false
    t.column "description", :string, :limit => 300, :default => "", :null => false
    t.column "user_id", :integer, :default => 0, :null => false
  end

  add_index "accounts", ["user_id"], :name => "user_id"

  create_table "categories", :force => true do |t|
    t.column "type_id", :integer, :default => 0, :null => false
    t.column "name", :string, :limit => 200, :default => "", :null => false
    t.column "description", :string, :limit => 500, :default => "", :null => false
    t.column "user_id", :integer, :default => 0, :null => false
  end

  add_index "categories", ["user_id"], :name => "user_id"
  add_index "categories", ["type_id"], :name => "type_id"

  create_table "despesas", :force => true do |t|
    t.column "user_id", :integer, :default => 0, :null => false
    t.column "category_id", :integer, :default => 0, :null => false
    t.column "account_id", :integer
    t.column "descricao", :string, :limit => 200, :default => "", :null => false
    t.column "valor", :float, :default => 0.0, :null => false
    t.column "data", :timestamp
  end

  add_index "despesas", ["category_id"], :name => "category_id"
  add_index "despesas", ["user_id"], :name => "user_id"
  add_index "despesas", ["account_id"], :name => "account_id"

  create_table "entries", :force => true do |t|
    t.column "user_id", :integer, :default => 0, :null => false
    t.column "type_id", :integer, :default => 0, :null => false
    t.column "category_id", :integer, :default => 0, :null => false
    t.column "description", :string, :limit => 500, :default => "", :null => false
    t.column "value", :float, :default => 0.0, :null => false
    t.column "created_on", :timestamp
    t.column "updated_on", :timestamp
    t.column "date", :timestamp
  end

  add_index "entries", ["user_id", "type_id", "category_id"], :name => "user_id"

  create_table "receitas", :force => true do |t|
    t.column "category_id", :integer, :default => 0, :null => false
    t.column "account_id", :integer
    t.column "user_id", :integer, :default => 0, :null => false
    t.column "descricao", :string, :limit => 200, :default => "", :null => false
    t.column "valor", :float, :default => 0.0, :null => false
    t.column "data", :timestamp
  end

  add_index "receitas", ["category_id"], :name => "category_id"
  add_index "receitas", ["user_id"], :name => "user_id"
  add_index "receitas", ["account_id"], :name => "account_id"

  create_table "sugestions", :force => true do |t|
    t.column "nome", :string, :limit => 200, :default => "", :null => false
    t.column "email", :string, :limit => 200, :default => "", :null => false
    t.column "sugestao", :string, :limit => 400, :default => "", :null => false
    t.column "created_on", :timestamp
  end

  create_table "taggings", :force => true do |t|
    t.column "tag_id", :integer
    t.column "taggable_id", :integer
    t.column "taggable_type", :string
    t.column "user_id", :integer, :default => 0, :null => false
  end

  add_index "taggings", ["tag_id", "taggable_id", "taggable_type"], :name => "taggings_tag_id_index"
  add_index "taggings", ["user_id"], :name => "user_id"

  create_table "tags", :force => true do |t|
    t.column "name", :string
  end

  add_index "tags", ["name"], :name => "tags_name_index"

  create_table "transactions", :force => true do |t|
    t.column "user_id", :integer
    t.column "account_id", :integer
    t.column "tipo", :string, :limit => 1
    t.column "descricao", :string, :limit => 200
    t.column "valor", :float, :limit => 9
    t.column "data", :timestamp
  end

  add_index "transactions", ["user_id"], :name => "user_id"
  add_index "transactions", ["account_id"], :name => "account_id"

  create_table "types", :force => true do |t|
    t.column "name", :string, :limit => 200, :default => "", :null => false
  end

  create_table "users", :force => true do |t|
    t.column "login", :string, :limit => 80, :default => "", :null => false
    t.column "salted_password", :string, :limit => 40, :default => "", :null => false
    t.column "email", :string, :limit => 60, :default => "", :null => false
    t.column "firstname", :string, :limit => 40
    t.column "lastname", :string, :limit => 40
    t.column "salt", :string, :limit => 40, :default => "", :null => false
    t.column "verified", :integer, :default => 0
    t.column "role", :string, :limit => 40
    t.column "security_token", :string, :limit => 40
    t.column "token_expiry", :datetime
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "logged_in_at", :datetime
    t.column "deleted", :integer, :default => 0
    t.column "delete_after", :datetime
  end

end
